name: Sync Repositories

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, closed]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "vixshan"
          git config user.email "vixshan@gmail.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/vikshan/amina.git

      - name: Fetch and sync with GitLab
        run: |
          git fetch gitlab
          git push -f gitlab refs/remotes/origin/*:refs/heads/*
          git push -f gitlab --tags
          git pull gitlab --allow-unrelated-histories || true
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git --all
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git --tags
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}